app_index:
    path: /
    controller: App\Controller\IndexController::index

app_paris_index:
      path: /paris
      controller: App\Controller\ParisController::index

app_paris_new:
      path: /paris/new/{equipe1}/{equipe2}
      controller: App\Controller\ParisController::parierMatch
      requirements:
                equipe1: "[a-z A-Z]{2,15}"
                equipe2: "[a-z A-Z]{2,15}"

app_match_index:
      path: /match
      controller: App\Controller\ParisController::indexMatch

app_team_index:
      path: /team
      controller: App\Controller\TeamController::index

app_team_new:
      path: /team/new
      controller: App\Controller\TeamController::newTeam

app_team_rejoindreTeam:
      path: /team/rejoindreTeam/{idUser}/{idTeam}
      controller: App\Controller\TeamController::rejoindreTeam
      requirements:
          idUser: '\d+'
          idTeam: '\d+'

app_team_listingUsers:
      path: /team/rejoindreTeam/{idTeam}
      controller: App\Controller\TeamController::listingUsers
      requirements:
          idTeam: '\d+'

app_user_index:
      path: /user
      controller: App\Controller\UserController::index

#app_user_newUser:
#     path: /user/new
#      controller: App\Controller\UserController::newUser

app_security_login:
      path: /login
      controller: App\Controller\SecurityController::login

app_security_logout:
      path: /logout
      controller: App\Controller\SecurityController::logout

app_admin:
      path: /admin
      controller: App\Controller\IndexController::admin

app_register:
      path: /register
      controller: App\Controller\UserController::newUser